[pytest]
markers =
    acceptance:         basic tests which checks acceptance to the pages
    authorization:      tests for authorization page only
    reset_password:     tests for reset password page only
    moderation:         tests for moderation tests only