## GitHUb actions for running the SL GUI tests
## This workflow is triggered on cron once a week on Sunday at 00:00

name: SL GUI Tests

on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## Checkout before using compose-action
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      ## Run docker-compose
      - name: Docker Compose 🐳
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yaml"
          up-flags: "--build"
          down-flags: "--volumes"
      ## Get current date
      - name: Get current date 📅
        id: date
        run: echo "date=$(date +'%F')" >> $GITHUB_OUTPUT # GITHUB_OUTPUT is a predefined environment variable
      ## Store artifacts
      - name: Store artifacts 📦
        uses: actions/upload-artifact@v2
        with:
          name: sl-gui-tests
          path: alurereport/${{ vars.REVISION }}
        env:
          REVISION: ${{ steps.date.outputs.date }}
      ## Download artifacts from previous step and publish to GitHub Pages using JamesIves/github-pages-deploy-action action
      - name: Download artifacts 📥
        uses: actions/download-artifact@v2
        with:
          name: sl-gui-tests
          path: alurereport/${{ vars.REVISION }}
        env:
          REVISION: ${{ steps.date.outputs.date }}
      ## Publish to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: alurereport/${{ vars.REVISION }} # The folder the action should deploy.
        env:
          REVISION: ${{ steps.date.outputs.date }}
